lb:
  image: indigodatacloudapps/dariah-repository:lb
  restart: "always"
  ports:
    - "80:80"
    - "443:443"
    - "8080:8080"
  links:
    - frontend
frontend:
  image: indigodatacloudapps/dariah-repository:frontend
  restart: "always"
  ports:
    - "81:80"
    - "444:443"
  links:
    - web
  volumes_from:
    - static
web:
  image: indigodatacloudapps/dariah-repository:web
  restart: "always"
  command: /usr/local/bin/python /code/zenodo/scripts/init.py
  # command: zenodo run -h 0.0.0.0 -p 5000
  ports:
    - "5000:5000"
  environment:
    - "APP_ACCOUNTS_SESSION_REDIS_URL=redis://cache:6379/1"
    - "APP_BROKER_URL=amqp://guest:guest@mq:5672//"
    - "APP_CACHE_REDIS_URL=redis://cache:6379/0"
    - "APP_CACHE_TYPE=redis"
    - "APP_CELERY_RESULT_BACKEND=redis://cache:6379/2"
    - "APP_SEARCH_ELASTIC_HOSTS=['es:9200']"
    - "APP_SECRET_KEY=CHANGE_ME"
    - "APP_SECURE_SESSION_COOKIE=True"
    - "APP_STATSD_HOST=statsd"
    - "APP_SQLALCHEMY_DATABASE_URI=postgresql://zenodo:zenodo@db/zenodo"
    - "APP_WSGI_PROXIES=2"
  links:
    - cache
    - es
    - mq
    - db
    - statsd
  volumes_from:
    - static
worker:
  image: indigodatacloudapps/dariah-repository:web
  restart: "always"
  command: "celery worker -A zenodo.celery --loglevel=INFO"
  environment:
    - "APP_ACCOUNTS_SESSION_REDIS_URL=redis://cache:6379/1"
    - "APP_BROKER_URL=amqp://guest:guest@mq:5672//"
    - "APP_CACHE_REDIS_URL=redis://cache:6379/0"
    - "APP_CACHE_TYPE=redis"
    - "APP_CELERY_RESULT_BACKEND=redis://cache:6379/2"
    - "APP_SEARCH_ELASTIC_HOSTS=['es:9200']"
    - "APP_SECRET_KEY=CHANGE_ME"
    - "APP_SECURE_SESSION_COOKIE=True"
    - "APP_STATSD_HOST=statsd"
    - "APP_SQLALCHEMY_DATABASE_URI=postgresql://zenodo:zenodo@db/zenodo"
    - "APP_WSGI_PROXIES=2"
  links:
    - cache
    - es
    - mq
    - db
    - statsd
  volumes_from:
    - static
statsd:
  image: indigodatacloudapps/dariah-repository:statsd
  restart: "always"
  ports:
    - "8125/udp:8125/udp"
  environment:
    - "ES_HOST=es"
    - "ES_PORT=9200"
  links:
    - es
cache:
  image: redis
  restart: "always"
  read_only: true
  ports:
    - "6379:6379"
db:
  image: postgres
  command: postgres
  restart: "always"
  environment:
    - "POSTGRES_DB=zenodo"
    - "POSTGRES_PASSWORD=zenodo"
    - "POSTGRES_USER=zenodo"
  ports:
    - "5432:5432"
  read_only: false
mq:
  image: rabbitmq:3-management
#  image: rabbitmq
  restart: "always"
  ports:
    - "15672:15672"
    - "5672:5672"
es:
  image: indigodatacloudapps/dariah-repository:elasticsearch
  restart: "always"
  ports:
    - "9200:9200"
    - "9300:9300"
static:
  restart: "no"
  image: indigodatacloudapps/dariah-repository:web
  command: tail -f /var/log/*
  user: zenodo
  volumes:
    - "/usr/local/var/instance/static"
    - "/usr/local/lib/python3.5/site-packages"
    - "/usr/local/var/data"
    - ".:/code/zenodo"
